name: "Get recent blog post"

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-readme-blog-post:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: "1. actions Checkout"
        uses: actions/checkout@v3      

      - name: "2. Get Current time"
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"
          
      - name: "3. Install dependencies"
        run:  |
          pip install --upgrade pip
          if [[ -f ./scripts/requirements.txt ]]
          then
            pip install -r ./scripts/requirements.txt
          else
            pip install bs4 requests
          fi 

      - name: "4. Run Script"
        run: |
          bash ./scripts/blog-post.sh

      - name: "5. Commit"
        env:
          TOKEN:  ${{ secrets.TOKEN }} 
          REPOSITORY:  ${{ github.repository }} 
          MESSAGE: "Update blog post"
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          bash ./scripts/commit.sh